name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
      - name: Lint
        if: matrix.node-version == '20.x'
        run: npm run lint
      - name: Prettier
        if: matrix.node-version == '20.x'
        run: npm run prettier:check
      - name: Test Node
        run: npm run test:node
      - name: Test Browser
        if: matrix.node-version == '20.x'
        run: |
          export PUPPETEER_EXECUTABLE_PATH=$(which google-chrome-stable)
          npm run test:browser
